#!/usr/bin/env bash

#---
# This scripts acts as a alias of `echo -n` function but
# is agnostic to operative system implementation.
#
# Prints a value without a new line break.
#
# @author   davorpatech
# @since    2021-08-01
# @version  2021-09-05
#
# @SOURCE:
#
#   https://davorpa.github.io/shell-utils/scripts/echon
#
# @RESOURCES:
# https://www.shellscript.sh/echo.html
# https://www.in-ulm.de/~mascheck/various/echo+printf/
#
# @LICENSE:
#
#   This program is free software. It comes without any warranty, to
#   the extent permitted by applicable law. You can redistribute it
#   and/or modify it under the terms of the Do What The Fuck You Want
#   To Public License, Version 2, as published by DavorpaTECH. See
#   https://davorpa.github.io/shell-utils/scripts/COPYING
#   for more details.
#
#---

# Detect features
if [ "X$(echo -n)" = "X-n" ]; then
    echo_n() { echo ${1+"$@"}"\c"; }
else
    echo_n() { echo -n ${1+"$@"}; }
fi

# shellcheck disable=SC2068
echo_n $@
