#!/usr/bin/env bash

# Usefull script/snippet to force syncing your forked main
# (local & remote origin) with their upstream sources.
#
# if there are some important changes in local/origin, make a stash first
#
# @author davorpatech
# @since 2021-07-01
#

#git remote add upstream https://github.com/some_user/some_repo
git fetch origin
git fetch upstream
git checkout gh_pages
git reset --hard upstream/gh_pages
git push origin gh_pages --force
