#!/usr/bin/env bash

#---
# This scripts acts as a shortcut to search git branches.
#
# @author   davorpatech
# @since    2021-09-18
# @version  2021-09-18
#
# @SOURCE:
#
#   https://davorpa.github.io/shell-utils/scripts/git-br-search
#
# @LICENSE:
#
#   This program is free software. It comes without any warranty, to
#   the extent permitted by applicable law. You can redistribute it
#   and/or modify it under the terms of the Do What The Fuck You Want
#   To Public License, Version 2, as published by DavorpaTECH. See
#   https://davorpa.github.io/shell-utils/scripts/COPYING
#   for more details.
#
#---

git branch | grep "$1"
