#!/bin/bash

# Usefull script/snippet to force syncing your forked main
# (local & remote origin) with their upstream sources.
#
# @author davorpatech
# @since 2021-07-01
#

#git remote add upstream https://github.com/some_user/some_repo
git fetch origin
git fetch upstream
git checkout main
git reset --hard upstream/main
git push origin main --force
