#!/usr/bin/env bash

#---
#
# A very slightly quicker way to credit an author on the latest commit.
#
# $1 - The full name of the author.
# $2 - The email address of the author.
#
# Examples
#
#   git credit "Zach Holman" zach@example.com
#
# @author   davorpatech
# @since    2021-09-18
# @version  2021-09-18
#
# @SOURCE:
#
#   https://davorpa.github.io/shell-utils/scripts/git-credit
#
# @LICENSE:
#
#   This program is free software. It comes without any warranty, to
#   the extent permitted by applicable law. You can redistribute it
#   and/or modify it under the terms of the Do What The Fuck You Want
#   To Public License, Version 2, as published by DavorpaTECH. See
#   https://davorpa.github.io/shell-utils/scripts/COPYING
#   for more details.
#
#---

git commit --amend --author "$1 <$2>" -C HEAD
