#!/usr/bin/env bash

#
# Usefull script/snippet to recover Github pull request's head 
# and continue review/improvement in other branch
# without the need of make a PR over the author forked repo
#
# @author davorpatech
# @since 2021-08-28
#

# prompt for data
read -p "Pull Request #" PR_NUMBER
read -p "Author @" PR_AUTHOR
read -p "Title (optional): " PR_TITLE

# @TODO: Sanatize inputs
PR_BRANCH="pr/$PR_AUTHOR/$PR_NUMBER"
[[ -z "${PR_TITLE// }" ]] && PR_BRANCH="$PR_BRANCH-$PR_TITLE"

git fetch upstream "pull/$PR_NUMBER/head:$PR_BRANCH"

read -p "Checkout PR branch '$PR_BRANCH' (y/n)? " answer
case ${answer:0:1} in
    y|Y|s|S )
        echo "Checkout PR branch: $PR_BRANCH ..."
        git checkout "$PR_BRANCH"
    ;;
    * )
        echo No
    ;;
esac
