#!/usr/bin/env bash

# This script shows you the name of upstream remote.
# If git repo is a fork, it returns `upstream`, if not `origin`
#
# @author   davorpatech
# @since    2021-08-31
# @version  2021-08-31
#
# @SOURCE:
#
#   https://davorpa.github.io/shell-utils/scripts/git-upstream-name
#
# @LICENSE:
#
#   This program is free software. It comes without any warranty, to
#   the extent permitted by applicable law. You can redistribute it
#   and/or modify it under the terms of the Do What The Fuck You Want
#   To Public License, Version 2, as published by Davorpa TECH. See
#   https://davorpa.github.io/shell-utils/scripts/COPYING
#   for more details.
#

git remote | grep -E -o '(upstream|origin)' | tail -1
