#!/usr/bin/env bash

#
# This script installs jq to be used eg in Git Bash for Windows
#
# jq is a lightweight and flexible command-line JSON processor.
# (https://stedolan.github.io/jq/)
#
# @author   davorpatech
# @since    2021-09-01
# @version  2021-09-01
#
# @SOURCE:
#
#   https://davorpa.github.io/shell-utils/scripts/install-jq
#
# @LICENSE:
#
#   This program is free software. It comes without any warranty, to
#   the extent permitted by applicable law. You can redistribute it
#   and/or modify it under the terms of the Do What The Fuck You Want
#   To Public License, Version 2, as published by DavorpaTECH. See
#   https://davorpa.github.io/shell-utils/scripts/COPYING
#   for more details.
#

ARCH=$(getconf LONG_BIT)

DL=
FILE=jq

case "$OSTYPE" in
  linux*)   DL="jq-linux$ARCH" ;;
  darwin*)  DL="jq-osx-amd64" ;;
  win*)     DL="jq-win$ARCH.exe"; FILE=jq.exe ;;
  msys*)    DL="jq-win$ARCH.exe"; FILE=jq.exe ;;
  cygwin*)  DL="jq-win$ARCH.exe"; FILE=jq.exe ;;
  bsd*)     DL="jq-linux$ARCH" ;;
  solaris*) DL="jq-linux$ARCH" ;;
  *)        echo -e "unknown: $OSTYPE" >&2
            exit 1
            ;;
esac

curl -L -o "$HOME/bin/$FILE" "https://github.com/stedolan/jq/releases/latest/download/$DL"
