#!/usr/bin/env bash

#---
#
# This scripts acts as a way of quickly tailing an `ls` command.
#
# `tail` is your long `ls`
#
# @author   davorpatech
# @since    2021-09-18
# @version  2021-09-18
# @credits  http://mmb.pcb.ub.es/~carlesfe/unix/tricks.txt
#
# @SOURCE:
#
#   https://davorpa.github.io/shell-utils/scripts/lt
#
# @LICENSE:
#
#   This program is free software. It comes without any warranty, to
#   the extent permitted by applicable law. You can redistribute it
#   and/or modify it under the terms of the Do What The Fuck You Want
#   To Public License, Version 2, as published by DavorpaTECH. See
#   https://davorpa.github.io/shell-utils/scripts/COPYING
#   for more details.
#
#---

ls -ltrsa "$@" | tail
