#!/usr/bin/env bash

# This script acts as a standard input pipe filter to trim it spaces from the right
#
# @author   davorpatech
# @since    2020-12-01
# @version  2020-12-01
#
# @SOURCE:
#
#   https://davorpa.github.io/shell-utils/scripts/rtrim
#
# @LICENSE:
#
#   This program is free software. It comes without any warranty, to
#   the extent permitted by applicable law. You can redistribute it
#   and/or modify it under the terms of the Do What The Fuck You Want
#   To Public License, Version 2, as published by DavorpaTECH. See
#   https://davorpa.github.io/shell-utils/scripts/COPYING
#   for more details.
#

sed -e 's/[[:space:]]*\$//g'
