#!/usr/bin/env bash

#---
#
# This script acts as a standard input pipe filter to trim it spaces from the right
#
# @author   davorpatech
# @since    2020-12-01
# @version  2021-08-30
#
# @SOURCE:
#
#   https://davorpa.github.io/shell-utils/scripts/rtrim
#
# @LICENSE:
#
#   This program is free software. It comes without any warranty, to
#   the extent permitted by applicable law. You can redistribute it
#   and/or modify it under the terms of the Do What The Fuck You Want
#   To Public License, Version 2, as published by DavorpaTECH. See
#   https://davorpa.github.io/shell-utils/scripts/COPYING
#   for more details.
#
#---

regex='s/[[:space:]]*$//g'
#check if args are suplied
if [ $# -eq 0 ]; then
    # as standard input pipe filter
    sed -e "$regex"
else
    # as single argument command

    opts="-n"  # no new line by default to support concat
    if [[ $1 == -e ]]; then # consume optional escape argument
        opts="${opts}e"
        shift
    fi

    # check if text argument is missing
    if [[ $# -ne 1 ]]; then
        cmdn=$(basename "$0")
        echo >&2 -e "usage: \e[32m$cmdn [-e] text\e[0m Pipe alternative: \e[32msome_command | $cmdn\e[0m."
        exit 4
    fi

    echo $opts "$1" | sed -e "$regex"
fi
